server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-service/public/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/zocial

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      -   name: gateway-service
          url: /v3/api-docs
      -   name: user-service
          url: /user-service/api-docs
    path: /swagger-ui.html

keycloak:
  realm: zocial
  server-url: http://localhost:8181
  client-id: zocial
  client -secret: xxx